name: Deploy blog source to github pages

on: 
  push:
    branches:
      - server

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@master

    - name: build
      run: npm install && npm run build
      
    - name: deploy
      uses: closertb/deploy-static-action@master
      with:
        name: 'doddle'
        type: 'server'
        token: ${{ secrets.Deploy_Token }}
        requestUrl: 'http://deploy.closertb.site/operate/deploy'
        dist: 'build'
        target: 'closertb.github.io'
        targetPath: '../closertb.github.io'
